{
 "title": "CPU",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Core Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "cpu_core_temperature", "legendFormat": "{{hostname}}-{{core}}" }
   ]
  },
  {
   "title": "CPU Core Load",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "cpu_core_load", "legendFormat": "{{hostname}}-{{core}}" }
   ]
  },
  {
   "title": "CPU Speed",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_detail", "legendFormat": "{{model}}" }
   ]
  }
 ]
}